### ISSUE TITLE
Move towards team created instances of pdfgen

### ISSUE THREAD

**Issue by TheUnnamedDude** [navikt/pdfgen#16]
The application was originally written for one team, however with more teams starting to use it there has been raised some concerns around how code changes will scale. I think the logical thing will be to remove templates from the main repository and each team will create their own instances of the application.

My proposed solution is to use a approach similar to baseimages where you extend the image built from this repository and add your own fonts, images and templates. This way we can also tag the images with a version tag, which will make it possible to do breaking changes without it affecting any of the teams using it. It would also be nice if we could generalize the handlebars helpers to make it easier to reuse it.

Pros of doing this would be:
* We maintain a open source approach and wont have a bunch of different feature sets in different forks
* Teams will get more control over the deployments of their templates
* Breaking changes wont affect anyone’s instances as long as they’re using a version tag
* Simpler troubleshooting as there will be less load on each set of pods
* pdfgen itself can be built and released to docker hub, which would make it reusable outside of NAV

**Comment by MikAoJk** [comment]
Done in, https://github.com/navikt/syfopdfgen
