### ISSUE TITLE
Investigate changing test framework

### ISSUE THREAD

**Issue by MikAoJk** [navikt/pdfgen#55]
As of now, spek is used as a test framework. 
I wonder if we should investigate 2 other choices

1. Kotest (https://kotest.io/)
Migration to Kotest will be quick and a very simple job

2. Junit5 (https://junit.org/junit5/)
This will probably take a little longer, but it is a very well-known and secure framework

**Comment by chinatsu** [comment]
I've had good experiences with Kotest. :) 
I'm not going to prioritize changing the test framework though

**Comment by MikAoJk** [comment]
in progress
