### ISSUE TITLE
API-utvidelse HTML -> PDF

### ISSUE THREAD

**Issue by knutnyg** [navikt/pdfgen#8]
Ved å la konsumentene selv forberede HTMLen til PDFen slipper vi veldig høy endringstakt på selve generatoren. Vi unngår også at et teams endringer kan påvirke andres teams fungerende templates i prod.

**Comment by einarbj** [comment]
@knutnyg Denne issuen er vel løst tidligere

**Comment by TheUnnamedDude** [comment]
#11 fikser denne
